# Generated by Django 3.1.7 on 2021-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210314_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_num',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
