# Generated by Django 3.1.7 on 2021-03-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210317_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='appID',
            field=models.CharField(default='730a447ceec841d28133f2415810742b', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='certification',
            field=models.CharField(default='7b0418bbd36b402eb1e32f3ae7a6a646', max_length=200),
        ),
    ]
