# Generated by Django 3.1.7 on 2021-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210318_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='meeting_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
